"""
Recipe records prepared for Pinecone vector database ingestion.

Generated by: v2/process_recipes.py
Schema: data/schemas/basicSchema.json

Usage:
    from v2.recipes_for_vector_db import RECIPE_RECORDS
"""

RECIPE_RECORDS = [
    {
        "_id": 'the-ultimate-chocolate-chip-cookie',
        "content": '# The Ultimate Chocolate Chip Cookie\n\nRating: 7.0/10\n\n## Ingredients\n\n1. 0.75 cup Butter Flavor Crisco\n2. 1.25 cups firmly packed light brown sugar\n3. 2 Tbsp milk\n4. 1 Tbsp vanilla\n5. 1 egg\n6. 1.75 cups all-purpose flour\n7. 1 tsp salt\n8. 0.75 tsp baking soda\n9. 1 cup semi-sweet chocolate chips\n10. 1 cup pecan pieces (optional)\n\n## Instructions\n\n1. Heat oven to 375°F. Combine Butter Flavor Crisco, brown sugar, milk and vanilla in large bowl. Beat at medium speed of electric mixer until creamy.\n2. Beat egg into creamed mixture. Combine flour, salt and baking soda and mix into creamed mixture until just blended.\n3. Stir in chocolate chips and pecan pieces. Drop rounded tablespoons (about 2 measuring tablespoons of dough) 3 inches apart on ungreased baking sheet. \n4. Bake at 375°F for 8 to 10 minutes for chewy cookies (cookies will appear moist - do not overbake), or 11 to 13 minutes for crisp cookies. Cool on baking sheet 2 minutes. Remove to cooling rack. 3 dozen 3-inch cookies.',
        "metadata": {
            "title": 'The Ultimate Chocolate Chip Cookie',
            "ingredients": '- 0.75 cup Butter Flavor Crisco\n- 1.25 cups firmly packed light brown sugar\n- 2 Tbsp milk\n- 1 Tbsp vanilla\n- 1 egg\n- 1.75 cups all-purpose flour\n- 1 tsp salt\n- 0.75 tsp baking soda\n- 1 cup semi-sweet chocolate chips\n- 1 cup pecan pieces (optional)',
            "instructions": '1. Heat oven to 375°F. Combine Butter Flavor Crisco, brown sugar, milk and vanilla in large bowl. Beat at medium speed of electric mixer until creamy.\n2. Beat egg into creamed mixture. Combine flour, salt and baking soda and mix into creamed mixture until just blended.\n3. Stir in chocolate chips and pecan pieces. Drop rounded tablespoons (about 2 measuring tablespoons of dough) 3 inches apart on ungreased baking sheet. \n4. Bake at 375°F for 8 to 10 minutes for chewy cookies (cookies will appear moist - do not overbake), or 11 to 13 minutes for crisp cookies. Cool on baking sheet 2 minutes. Remove to cooling rack. 3 dozen 3-inch cookies.',
            "rating": 7.0,
            "diet": ['vegetarian'],
            "protein": ['egg'],
            "cuisine": ['american'],
            "meal_type": ['dessert'],
            "difficulty": 'medium',
            "prepTimeMinutes": 20,
        },
    }
]
